apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: knative-pipeline-run-
spec:
  pipelineRef:
    name: knative-pipeline
  params:
    - name: application
      value: quarkus-hello-world
    - name: source-repo-url
      value: https://github.com/marrober/quarkus-hello-world.git
    - name: source-revision
      value: main
    - name: short-source-revision
      value: "main"
    - name: deployment-repo-url
      value: github.com/marrober/quarkus-hello-world-deployment.git
    - name: github-repo-name 
      value: quarkus-hello-world-deployment
    - name: deployment-revision
      value: "main"
    - name: dockerfile
      value: ./src/main/docker/Dockerfile.jvm
    - name: image-registry
      value: image-registry.openshift-image-registry.svc.cluster.local:5000
    - name: image-repository
      value: cicd
    - name: STORAGE_DRIVER
      value: vfs
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
#    persistentvolumeclaim:
#      claimName: source-pvc 
  - name: maven-settings
    configMap: 
       name: maven
  - name: knative-kustomize-base
    configMap: 
       name: knative-kustomize-base
  - name: knative-kustomize-environment
    configMap: 
       name: knative-kustomize-environment
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi